name = "Sticky Recipe"
description = "Makes a recipe sticky to remind you what you are working on"
author = "rskuipers"
version = "1.1.5"
forumthread = "/"
icon_atlas = "modicon.xml"
icon = "modicon.tex"
client_only_mod = true
dont_starve_compatible = true
reign_of_giants_compatible = true
dst_compatible = true
api_version = 10
